// Package analytics 提供只读的图结构分析能力。
package analytics
import("sort";"gographdb/internal/graph";)
type Degree struct{VertexID uint64 `json:"vertexId"`;In int `json:"in"`;Out int `json:"out"`;Total int `json:"total"`;}
type Rank struct{VertexID uint64 `json:"vertexId"`;Score float64 `json:"score"`;}
type Report struct{Vertices int `json:"vertices"`;Edges int `json:"edges"`;Components int `json:"components"`;Isolated int `json:"isolated"`;SelfLoops int `json:"selfLoops"`;TopDegrees []Degree `json:"topDegrees"`;PageRank []Rank `json:"pageRank"`;}
type SchemaItem struct{Label string `json:"label"`;Count int `json:"count"`;Properties map[string][]graph.ValueType `json:"properties"`;};type SchemaReport struct{Vertices int `json:"vertices"`;Edges int `json:"edges"`;VertexLabels []SchemaItem `json:"vertexLabels"`;EdgeLabels []SchemaItem `json:"edgeLabels"`;};type schemaBucket struct{Count int;Properties map[string]map[graph.ValueType]bool;};
// Schema 汇总图中节点、边标签及其属性类型。
func Schema(g*graph.Graph)SchemaReport{vertices,edges,_,_:=g.Snapshot();add:=func(items map[string]*schemaBucket,label string,properties map[string]graph.PropertyValue){item:=items[label];if item==nil{item=&schemaBucket{Properties:map[string]map[graph.ValueType]bool{}};items[label]=item};item.Count++;for name,value:=range properties{if item.Properties[name]==nil{item.Properties[name]=map[graph.ValueType]bool{}};item.Properties[name][value.Type]=true}};build:=func(items map[string]*schemaBucket)[]SchemaItem{labels:=make([]string,0,len(items));for label:=range items{labels=append(labels,label)};sort.Strings(labels);out:=make([]SchemaItem,0,len(labels));for _,label:=range labels{item:=items[label];properties:=map[string][]graph.ValueType{};for name,types:=range item.Properties{for valueType:=range types{properties[name]=append(properties[name],valueType)};sort.Slice(properties[name],func(i,j int)bool{return properties[name][i]<properties[name][j]})};out=append(out,SchemaItem{label,item.Count,properties})};return out};vertexLabels,edgeLabels:=map[string]*schemaBucket{},map[string]*schemaBucket{};for _,vertex:=range vertices{labels:=vertex.Labels;if len(labels)==0{labels=[]string{"_unlabeled"}};for _,label:=range labels{add(vertexLabels,label,vertex.Properties)}};for _,edge:=range edges{add(edgeLabels,edge.Label,edge.Properties)};return SchemaReport{len(vertices),len(edges),build(vertexLabels),build(edgeLabels)}}

type QualityIssue struct{Code string `json:"code"`;Count int `json:"count"`;};type QualityReport struct{Vertices int `json:"vertices"`;Edges int `json:"edges"`;Healthy bool `json:"healthy"`;Issues []QualityIssue `json:"issues"`;};
// Quality 检查标签、属性、孤立节点和自环等数据完整性信号。
func Quality(g*graph.Graph)QualityReport{vertices,edges,_,_:=g.Snapshot();r:=QualityReport{Vertices:len(vertices),Edges:len(edges),Issues:[]QualityIssue{}};connected:=map[uint64]bool{};unlabeled,propertyless:=0,0;for _,vertex:=range vertices{if len(vertex.Labels)==0{unlabeled++};if len(vertex.Properties)==0{propertyless++};connected[vertex.ID]=false};edgeWithoutProperties,selfLoops:=0,0;for _,edge:=range edges{if edge.From==edge.To{selfLoops++};if len(edge.Properties)==0{edgeWithoutProperties++};connected[edge.From]=true;connected[edge.To]=true};isolated:=0;for _,isConnected:=range connected{if !isConnected{isolated++}};add:=func(code string,count int){if count>0{r.Issues=append(r.Issues,QualityIssue{code,count})}};add("unlabeled_vertices",unlabeled);add("vertices_without_properties",propertyless);add("edges_without_properties",edgeWithoutProperties);add("isolated_vertices",isolated);add("self_loops",selfLoops);r.Healthy=len(r.Issues)==0;return r}

// Build 计算弱连通分量、度中心性和 20 轮 PageRank；结果按分数稳定排序。
func Build(g*graph.Graph,limit int)Report{if limit<1{limit=10};if limit>100{limit=100};vertices,edges,_,_:=g.Snapshot();r:=Report{Vertices:len(vertices),Edges:len(edges)};if len(vertices)==0{return r};ids:=map[uint64]struct{}{};in,out:=map[uint64]int{},map[uint64]int{};near:=map[uint64]map[uint64]struct{}{};for _,v:=range vertices{ids[v.ID]=struct{}{};near[v.ID]=map[uint64]struct{}{}};for _,e:=range edges{if _,ok:=ids[e.From];!ok{continue};if _,ok:=ids[e.To];!ok{continue};out[e.From]++;in[e.To]++;if e.From==e.To{r.SelfLoops++;continue};near[e.From][e.To]=struct{}{};near[e.To][e.From]=struct{}{}};degrees:=make([]Degree,0,len(vertices));rank:=map[uint64]float64{};for id:=range ids{degrees=append(degrees,Degree{id,in[id],out[id],in[id]+out[id]});rank[id]=1/float64(len(ids));if in[id]+out[id]==0{r.Isolated++}};seen:=map[uint64]bool{};for id:=range ids{if seen[id]{continue};r.Components++;queue:=[]uint64{id};seen[id]=true;for len(queue)>0{current:=queue[0];queue=queue[1:];for next:=range near[current]{if !seen[next]{seen[next]=true;queue=append(queue,next)}}}};for turn:=0;turn<20;turn++{next:=map[uint64]float64{};dangling:=0.0;for id:=range ids{if out[id]==0{dangling+=rank[id]}};base:=(1-.85)/float64(len(ids))+.85*dangling/float64(len(ids));for id:=range ids{next[id]=base};for _,e:=range edges{if out[e.From]>0{next[e.To]+=.85*rank[e.From]/float64(out[e.From])}};rank=next};sort.Slice(degrees,func(i,j int)bool{if degrees[i].Total==degrees[j].Total{return degrees[i].VertexID<degrees[j].VertexID};return degrees[i].Total>degrees[j].Total});for _,item:=range degrees{r.PageRank=append(r.PageRank,Rank{item.VertexID,rank[item.VertexID]})};sort.Slice(r.PageRank,func(i,j int)bool{if r.PageRank[i].Score==r.PageRank[j].Score{return r.PageRank[i].VertexID<r.PageRank[j].VertexID};return r.PageRank[i].Score>r.PageRank[j].Score});if len(degrees)>limit{degrees=degrees[:limit]};if len(r.PageRank)>limit{r.PageRank=r.PageRank[:limit]};r.TopDegrees=degrees;return r}
